import 'dart:io';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/transaction_model.dart';
import '../services/transaction_service.dart';

class PdfService {
  final TransactionService _transactionService = TransactionService();

  Future<void> generateMonthlyReport(
    BuildContext context,
    int year,
    int month,
  ) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      throw Exception('User not logged in');
    }

    final transactions = await _transactionService.getTransactions().first;
    final monthTransactions = transactions
        .where((t) => t.date.year == year && t.date.month == month)
        .toList();

    if (monthTransactions.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No transactions for this month')),
      );
      return;
    }

    double income = 0;
    double expense = 0;
    for (var t in monthTransactions) {
      if (t.type == TransactionType.income) {
        income += t.amount;
      } else {
        expense += t.amount;
      }
    }
    final balance = income - expense;

    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        margin: pw.EdgeInsets.all(40),
        build: (context) {
          return [
            pw.Center(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                children: [
                  pw.Text(
                    'ExpenseX',
                    style: pw.TextStyle(
                      fontSize: 28,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.purple,
                    ),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    'Monthly Report',
                    style: pw.TextStyle(fontSize: 18, color: PdfColors.grey700),
                  ),
                  pw.Text(
                    '${_monthName(month)} $year',
                    style: pw.TextStyle(
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.Divider(),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
              children: [
                _buildSummaryCard('Income', income, PdfColors.green),
                _buildSummaryCard('Expense', expense, PdfColors.red),
                _buildSummaryCard(
                  'Balance',
                  balance,
                  balance >= 0 ? PdfColors.green : PdfColors.red,
                ),
              ],
            ),
            pw.SizedBox(height: 30),

            pw.Text(
              'Category Breakdown',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),
            ..._buildCategoryTable(monthTransactions),
            pw.SizedBox(height: 20),

            pw.Text(
              'Transactions',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),
            _buildTransactionTable(monthTransactions),

            pw.SizedBox(height: 30),
            pw.Center(
              child: pw.Text(
                'Generated by ExpenseX',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
            ),
          ];
        },
      ),
    );

    try {
      final bytes = await pdf.save();
      final tempFile = File(
        '${Directory.systemTemp.path}/ExpenseX_Report_${year}_${month.toString().padLeft(2, '0')}.pdf',
      );
      await tempFile.writeAsBytes(bytes);
      await Printing.sharePdf(
        bytes: bytes,
        filename:
            'ExpenseX_Report_${year}_${month.toString().padLeft(2, '0')}.pdf',
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error generating PDF: ${e.toString()}')),
      );
    }
  }

  pw.Widget _buildSummaryCard(String label, double amount, PdfColor color) {
    return pw.Container(
      padding: pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            '₹${amount.toStringAsFixed(2)}',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  List<pw.Widget> _buildCategoryTable(List<TransactionModel> transactions) {
    Map<String, double> categoryTotals = {};
    for (var t in transactions.where(
      (t) => t.type == TransactionType.expense,
    )) {
      categoryTotals[t.category] = (categoryTotals[t.category] ?? 0) + t.amount;
    }
    final entries = categoryTotals.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    return [
      pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey300),
        children: [
          pw.TableRow(
            decoration: pw.BoxDecoration(color: PdfColors.grey100),
            children: [
              pw.Padding(
                padding: pw.EdgeInsets.all(8),
                child: pw.Text(
                  'Category',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
              ),
              pw.Padding(
                padding: pw.EdgeInsets.all(8),
                child: pw.Container(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text(
                    'Amount',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                ),
              ),
            ],
          ),
          ...entries.map((entry) {
            return pw.TableRow(
              children: [
                pw.Padding(
                  padding: pw.EdgeInsets.all(8),
                  child: pw.Text(entry.key),
                ),
                pw.Padding(
                  padding: pw.EdgeInsets.all(8),
                  child: pw.Container(
                    alignment: pw.Alignment.centerRight,
                    child: pw.Text('₹${entry.value.toStringAsFixed(2)}'),
                  ),
                ),
              ],
            );
          }),
        ],
      ),
    ];
  }

  pw.Widget _buildTransactionTable(List<TransactionModel> transactions) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: PdfColors.grey100),
          children: [
            pw.Padding(
              padding: pw.EdgeInsets.all(8),
              child: pw.Text(
                'Date',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.Padding(
              padding: pw.EdgeInsets.all(8),
              child: pw.Text(
                'Category',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.Padding(
              padding: pw.EdgeInsets.all(8),
              child: pw.Text(
                'Type',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.Padding(
              padding: pw.EdgeInsets.all(8),
              child: pw.Container(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  'Amount',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
              ),
            ),
          ],
        ),
        ...transactions.take(20).map((t) {
          return pw.TableRow(
            children: [
              pw.Padding(
                padding: pw.EdgeInsets.all(6),
                child: pw.Text('${t.date.day}/${t.date.month}/${t.date.year}'),
              ),
              pw.Padding(
                padding: pw.EdgeInsets.all(6),
                child: pw.Text(t.category),
              ),
              pw.Padding(
                padding: pw.EdgeInsets.all(6),
                child: pw.Text(
                  t.type == TransactionType.income ? 'Income' : 'Expense',
                ),
              ),
              pw.Padding(
                padding: pw.EdgeInsets.all(6),
                child: pw.Container(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text(
                    '₹${t.amount.toStringAsFixed(2)}',
                    style: pw.TextStyle(
                      color: t.type == TransactionType.income
                          ? PdfColors.green
                          : PdfColors.red,
                    ),
                  ),
                ),
              ),
            ],
          );
        }),
      ],
    );
  }

  String _monthName(int month) {
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    return months[month - 1];
  }
}
